export const DRAG_TYPES = {
  NODE_COMPONENT: "NODE_COMPONENT",
};

export const types = {
  ON_CHANGE_NODE: "ON_CHANGE_NODE",
  ON_CHANGE_SIDEBAR: "ON_CHANGE_SIDEBAR",
  ON_CHANGE_WORKFLOW: "ON_CHANGE_WORKFLOW",
  ON_ADD_WORKFLOW: "ON_ADD_WORKFLOW",
  ON_UPDATE_WORKFLOW: "ON_UPDATE_WORKFLOW",
};
